// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjmXGH-W2n8NKXF2x3cj8AYdoImm1_Yjs',
    appId: '1:766850064831:web:e16ee0f09ad1bd07d6410a',
    messagingSenderId: '766850064831',
    projectId: 'census-app-6dabf',
    authDomain: 'census-app-6dabf.firebaseapp.com',
    storageBucket: 'census-app-6dabf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhp8k2QsN7rlaUL3j9uZAEJoVaSkmuxAI',
    appId: '1:766850064831:android:3736c7d1519a3e3bd6410a',
    messagingSenderId: '766850064831',
    projectId: 'census-app-6dabf',
    storageBucket: 'census-app-6dabf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd_D3sa_78anH7OGi7M8RmwqYRyVUniMA',
    appId: '1:766850064831:ios:cfc4ba95c8fa0515d6410a',
    messagingSenderId: '766850064831',
    projectId: 'census-app-6dabf',
    storageBucket: 'census-app-6dabf.appspot.com',
    iosClientId: '766850064831-vn7ge7dl67n0nd08p0r9ee5osd674oda.apps.googleusercontent.com',
    iosBundleId: 'com.example.censusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd_D3sa_78anH7OGi7M8RmwqYRyVUniMA',
    appId: '1:766850064831:ios:6f4bf12697a2d207d6410a',
    messagingSenderId: '766850064831',
    projectId: 'census-app-6dabf',
    storageBucket: 'census-app-6dabf.appspot.com',
    iosClientId: '766850064831-ffi51ea04a5t8l1pj9vnhknmnoji1v3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.censusApp.RunnerTests',
  );
}
